kind: Service
apiVersion: v1
metadata:
  name: dapr-kv
  namespace: {{.Release.Namespace}}
  labels:
    app: dapr-kv
spec:
  selector:
    app: dapr-kv
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-kv
  namespace: {{.Release.Namespace}}
  labels:
    app: dapr-kv
spec:
  selector:
    matchLabels:
      app: dapr-kv
  template:
    metadata:
      labels:
        app: dapr-kv
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-kv"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
    spec:
      nodeSelector:
        offMeshNodeType: cpu
      containers:
      - name: dapr-kv
        image: registry.cn-hangzhou.aliyuncs.com/jkhe/statestore:hjk-1.00
        env:
        - name: APP_PORT
          value: "3000"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
