apiVersion: batch/v1
kind: Job
metadata:
  name: wrk2-prometheus
  namespace: {{.Release.Namespace}}
  labels:
    jobgroup: wrk2-prometheus
spec:
  template:
    metadata:
      name: wrk2-prometheus
      annotations:
        linkerd.io/inject: enabled
      labels:
        jobgroup: wrk2-prometheus
        app: wrk2-prometheus
        custom-affinity: load-generator-node
    spec:
      nodeSelector:
        role: benchmark
        offMeshNodeType: cpu
      restartPolicy: Never
      volumes:
        - name: tempfs
          emptyDir:
            medium: Memory
      shareProcessNamespace: true
      containers:
      - name: wrk2-prometheus
        image: {{ .Values.wrk2.appImage }}
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BIND_SERVICE
              - KILL
        volumeMounts:
          - name: tempfs
            mountPath: "/tmpfs"
        args:
          - -p
          - "null"
          - -c
          - "{{.Values.wrk2.connections}}"
          - -d
          - "{{.Values.wrk2.duration}}"
          - -r
          - "{{.Values.wrk2.RPS}}"
          - -i
          - "{{.Values.wrk2.initDelay}}"
          - -o
          - "{{.Values.wrk2.timeout}}"
{{- if eq .Values.wrk2.app.name "emojivoto" }}
{{- template "emojivotoURLs" . }}
{{- else if eq .Values.wrk2.app.name "bookinfo" }}
{{- template "bookinfoURLs" . }}
{{- end }}
