lokoctl:
  branch: master

charts:
  branch: master

terraform:
  version: 0.13.5

helm:
  version: 3.4.0

sshKey:
  public:
  private:

# Possible values: [equinix-metal, aws].
benchmarkingClusterCloud:

clouds:
  aws:
    accessKeyID:
    secretAccessKey:
    defaultRegion: eu-central-1
    route53Zone:
    route53ZoneID:

  packet:
    token:
    projectID:
    regionEIPs:
