apiVersion: v1
kind: Secret
metadata:
  name: cloud-secrets
  namespace: orchestrator
data:
  {{if .Values.clouds.em.token}}
  EQUINIX_METAL_AUTH_TOKEN: {{ .Values.clouds.em.token | b64enc }}
  {{end}}
  {{if .Values.clouds.em.projectID}}
  EQUINIX_METAL_PROJECT_ID: {{ .Values.clouds.em.projectID | b64enc }}
  {{end}}
  {{if .Values.clouds.aws.accessKeyID}}
  AWS_ACCESS_KEY_ID: {{ .Values.clouds.aws.accessKeyID | b64enc }}
  {{end}}
  {{if .Values.clouds.aws.secretAccessKey}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.clouds.aws.secretAccessKey | b64enc }}
  {{end}}
  {{if .Values.clouds.aws.defaultRegion}}
  AWS_DEFAULT_REGION: {{ .Values.clouds.aws.defaultRegion | b64enc }}
  {{end}}
  {{if .Values.clouds.aws.route53Zone}}
  AWS_ROUTE53_ZONE: {{ .Values.clouds.aws.route53Zone | b64enc }}
  {{end}}
  {{if .Values.clouds.aws.route53ZoneID}}
  AWS_ROUTE53_ZONE_ID: {{ .Values.clouds.aws.route53ZoneID | b64enc }}
  {{end}}
