apiVersion: v1
kind: Secret
metadata:
  name: cloud-secrets
  namespace: orchestrator
data:
  PACKET_AUTH_TOKEN: {{ .Values.clouds.packet.token | b64enc }}
  PACKET_PROJECT_ID: {{ .Values.clouds.packet.projectID | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.clouds.aws.accessKeyID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.clouds.aws.secretAccessKey | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.clouds.aws.defaultRegion | b64enc }}
  AWS_ROUTE53_ZONE: {{ .Values.clouds.aws.route53Zone | b64enc }}
  AWS_ROUTE53_ZONE_ID: {{ .Values.clouds.aws.route53ZoneID | b64enc }}
