apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-install-configs
  namespace: orchestrator
data:
{{ if eq .Values.benchmarkingClusterCloud "equinix-metal" }}
{{ (.Files.Glob "cluster-install-configs/equinix-metal/equinix-metal.lokocfg").AsConfig | indent 2 }}
{{ (.Files.Glob "cluster-install-configs/equinix-metal/equinix-metal.vars.envsubst").AsConfig | indent 2 }}
{{ end }}
{{ (.Files.Glob "cluster-install-configs/run.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "cluster-install-configs/cleanup.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "cluster-install-configs/cleanup-setup.sh").AsConfig | indent 2 }}
