apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orchestrator
  name: orchestrator
  namespace: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        pvc: binaries
    spec:
      containers:
      - image: quay.io/kinvolk/smb-orchestrator
        name: orchestrator
        env:
        - name: REGION_EIPS
          value: {{.Values.clouds.packet.regionEIPs}}
        volumeMounts:
        - name: binaries
          mountPath: /binaries
        - name: cluster-install-configs
          mountPath: /scripts
      serviceAccountName: orchestrator
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: pvc
                operator: In
                values:
                - binaries
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: binaries
        persistentVolumeClaim:
          claimName: binaries
      - name: cluster-install-configs
        configMap:
          name: cluster-install-configs
