apiVersion: batch/v1
kind: Job
metadata:
  name: download-helm
  namespace: orchestrator
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: download-helm
        image: alpine/helm:{{.Values.helm.version}}
        command:
        - sh
        args:
        - -c
        - 'mv /usr/bin/helm /binaries'
        volumeMounts:
        - name: binaries
          mountPath: /binaries
      serviceAccountName: downloader
      automountServiceAccountToken: false
      volumes:
      - name: binaries
        persistentVolumeClaim:
          claimName: binaries
