apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator
  namespace: orchestrator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobrunner
  namespace: orchestrator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: downloader
  namespace: orchestrator
