apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  namespace: {{.Release.Namespace}}
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      nodeSelector:
        role: workload
        offMeshNodeType: cpu
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.15.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BIND_SERVICE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  namespace: {{.Release.Namespace}}
  labels:
    app: ratings
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      nodeSelector:
        role: workload
        offMeshNodeType: cpu
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.15.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BIND_SERVICE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  namespace: {{.Release.Namespace}}
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      nodeSelector:
        role: workload
        offMeshNodeType: cpu
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.15.1
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BIND_SERVICE
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  namespace: {{.Release.Namespace}}
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      nodeSelector:
        role: workload
        offMeshNodeType: cpu
      containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.15.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BIND_SERVICE
      volumes:
      - name: tmp
        emptyDir: {}
