apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: {{.Release.Namespace}}
  labels:
    app: details
    service: details
    app: bookinfo
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: {{.Release.Namespace}}
  labels:
    app: ratings
    service: ratings
    app: bookinfo
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: {{.Release.Namespace}}
  labels:
    app: reviews
    service: reviews
    app: bookinfo
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: {{.Release.Namespace}}
  labels:
    app: productpage
    service: productpage
    app: bookinfo
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
