{{ if .Values.enableLinkerdServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    servicemesh: linkerd
    app: bookinfo
    release: prometheus-operator
  name: linkerd-proxies
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: bookinfo
  endpoints:
  - targetPort: 4191
{{ end }}
