apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  namespace: {{.Release.Namespace}}
  labels:
    account: details
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  namespace: {{.Release.Namespace}}
  labels:
    account: ratings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  namespace: {{.Release.Namespace}}
  labels:
    account: productpage
